import { type NextPage } from "next";
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

import { api, type RouterOutputs } from "~/utils/api";
import Image from "next/image";

const CreateMovieWizard = () => {
  const { user } = useUser()

  if (!user) return null

  return (
    <div className="flex w-full gap-4">
      <Image
        src={user?.profileImageUrl}
        alt={`${user?.username} profile image` || "profile image"}
        className="rounded-full object-cover"
        width={56}
        height={56}
      />

      <input
        placeholder="Type some movie name..."
        className="bg-transparent text-xl grow outline-none"
      />
    </div>
  )
}

type PostViewProps = RouterOutputs["movies"]["getAll"][number]

const PostView = (props: PostViewProps) => {
  const { movie, user } = props

  return (
    <div key={movie.id} className="p-6 flex items-center gap-4 border-b">
      <Image
        src={user.avatar}
        alt={`${user.username} profile image}`}
        className="rounded-full object-cover"
        width={64}
        height={64}
      />

      <div className="flex flex-col text-slate-300">
        <div>
          <span>{`@${user.username}`}</span>
          <span className="">{` · ${dayjs(movie.createdAt).fromNow()}`}</span>
        </div>


        <h2 className="text-lg">{movie.title}</h2>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const { isSignedIn } = useUser();

  const { data, isLoading, isError, } = api.movies.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>
  if (isError) return <h1>Something went wrong</h1>

  return (
    <>
      <Head>
        <title>Cine Movies</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
        <div className="mx-auto w-full max-w-2xl border-x ">
          <div className="flex items-center justify-between border-b p-8">
            {!isSignedIn && (
              <div >
                <SignInButton mode="modal">SIGN IN</SignInButton>
              </div>
            )}
            {!!isSignedIn && (
              <>
                <CreateMovieWizard />
                <SignOutButton>
                  SIGN OUT
                </SignOutButton>
              </>
            )}
          </div>

          {data?.map(({ user, movie }) => (
            <PostView key={movie.id} user={user} movie={movie} />
          ))}
        </div>
      </main >
    </>
  );
};

export default Home;
